repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        files: r"*.py""
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-toml
  - repo: local
    hooks:
      - id: lint
        name: lint
        stages: [commit]
        language: system
        entry: make lint
      - id: format
        name: format
        stages: [commit]
        language: system
        entry: make check
        types: [python]
