version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: python_ddd
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 6432:5432
  redis:
    image: redis:6.2
    restart: always
    ports:
      - 6380:6379
