"""empty message

Revision ID: 1a3584cad4c8
Revises: fd0bfd7d3edb
Create Date: 2021-10-06 17:28:41.185880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3584cad4c8'
down_revision = 'fd0bfd7d3edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations_view',
    sa.Column('orderid', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('batchref', sa.String(length=255), nullable=True)
    )
    op.create_table('batches_view',
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True)
    )
    op.create_table('products_view',
    sa.Column('sku', sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_view')
    op.drop_table('batches_view')
    op.drop_table('allocations_view')
    # ### end Alembic commands ###
