"""empty message

Revision ID: 313ffab7ab2c
Revises: 6aa7691b7cfa
Create Date: 2021-09-24 12:48:15.209741

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "313ffab7ab2c"
down_revision = "6aa7691b7cfa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sku", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    op.add_column("batches", sa.Column("product_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "batches", "products", ["product_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "batches", type_="foreignkey")
    op.drop_column("batches", "product_id")
    op.drop_table("products")
    # ### end Alembic commands ###
