"""empty message

Revision ID: def38e002abb
Revises: 1a3584cad4c8
Create Date: 2021-10-07 20:30:43.039054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def38e002abb'
down_revision = '1a3584cad4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches_view', sa.Column('qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches_view', 'qty')
    # ### end Alembic commands ###
